### ISSUE TITLE
ioctl fail: Invalid argument

### ISSUE THREAD

**Issue by kimkim19642004** [transcend-information/RaspberryPi-SDcard-SMARTQuery#1]
Is the source code up to date?
It doesn't work well in my environment.

**[Environment]**
MicroSD: 430T 64GB
Card Reader: RDF5
OS: Fedora Linux 35 (Workstation Edition)
Device Name: /dev/sdb, /dev/sdb1

**[Execution result]**
sudo ./mmc smtbuffer /dev/sdb
ioctl fail: Invalid argument
CMD56 function fail, /dev/sdb

sudo ./mmc smtbuffer /dev/sdb1
ioctl fail: Invalid argument
CMD56 function fail, /dev/sdb1

**Comment by TSJerryWu** [comment]
Hi kimkim19642004, 

The project only support that reading the smart information of Micro SD card via internal Micro SD card slot now. Thanks.

**Comment by kimkim19642004** [comment]
Thank you for your reply. I now realize that I was misunderstanding.

/dev/sdb1 <-- This is a **USB Device**.

**Comment by zoldaten** [comment]
i see the same error on raspberry pi Raspbian Bullseye:
```
sudo ./mmc smtbuffer /dev/mmcblk0

ioctl fail: Connection timed out
CMD56 function fail, /dev/mmcblk0
```
it seems i built everything right:
![Screenshot_3](https://github.com/transcend-information/RaspberryPi-SDcard-SMARTQuery/assets/29411817/27ae7b22-d720-40be-995a-0938be0fa89e)

**Comment by kimkim19642004** [comment]
Do you know **"Scope Pro CLI"**?

It's worth a try if you're using _**Ubuntu**_.

See: https://www.transcend-info.com/manual/ScopeProCLI/EN/

**Comment by slcheng** [comment]
We have tested well in Raspbian Bullseye 32bit and 64bit. The project only works for MicroSD 430T / 450I / 460I / 460T. Would you check the MicroSD model on hand  ?

**Comment by zoldaten** [comment]
sandisk ...not my way... thanks
